files:
  - source: /l10n/en-US.yml
    translation: /l10n/%locale%.yml
pull_request_title: "chore(l10n): Sync with Crowdin"
pull_request_labels: ["l10n"]
commit_message: "chore(l10n): Update %language% translations"
append_commit_message: false
