name: Crowdin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
          download_sources: true
          download_translations: true
          push_translations: true
          push_sources: true
          source: "l10n/en.yml"
          translation: "l10n/%locale%.yml"
          commit_message: "chore(l10n): Update translations"
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
